SBCL ?= sbcl
SBCL_FLAGS = --noinform --non-interactive

.PHONY: all test test-torture check clean examples repl repl-loader \
        bpftrace-parse-test bpftrace-runtime-test

all: whistler

# Build standalone binary. The program-op is on whistler/cli (which
# pulls in whistler + whistler/loader + symbolize + bpftrace); the
# bare "whistler" system has no :build-operation and would just load
# without producing an executable.
whistler: whistler.asd $(wildcard src/*.lisp) $(wildcard src/loader/*.lisp) $(wildcard src/symbolize/*.lisp) $(wildcard src/bpftrace/*.lisp)
	$(SBCL) $(SBCL_FLAGS) \
		--eval '(require :asdf)' \
		--eval '(push #p"./" asdf:*central-registry*)' \
		--eval '(asdf:make "whistler/cli")'

# Compile examples
examples: all
	./whistler compile examples/count-xdp.lisp -o examples/count-xdp.bpf.o

# Run all tests
test:
	$(SBCL) $(SBCL_FLAGS) \
		--eval '(require :asdf)' \
		--eval '(push #p"./" asdf:*central-registry*)' \
		--eval '(asdf:load-system "whistler/tests")' \
		--eval '(unless (whistler/tests:run-tests) (uiop:quit 1))'

# Run torture tests with kernel verification (requires sudo for CAP_BPF)
test-torture:
	sudo env PATH="$(PATH)" $(SBCL) $(SBCL_FLAGS) \
		--eval '(require :asdf)' \
		--eval '(push #p"./" asdf:*central-registry*)' \
		--eval '(asdf:load-system "whistler/tests")' \
		--eval '(unless (fiveam:run! (quote whistler/tests::torture-suite)) (uiop:quit 1))'

check: test

# bpftrace's tools-parsing-test.sh equivalent — runs each script under
# bpftrace's tools/ directory through `whistler bpftrace --dump' and
# verifies parser + codegen accept it. Doesn't require root or a
# loaded kernel. BPFTRACE_TOOLS overrides the source directory.
bpftrace-parse-test: whistler
	./scripts/bpftrace-tools-parse.sh

# Plug whistler into bpftrace's own runtime test engine (Python). The
# engine reads NAME/RUN/EXPECT cases from bpftrace's tests/runtime/
# tree; we wire it up by symlinking whistler under the name `bpftrace'
# (the binary's argv[0] dispatch makes that an alias) and pointing
# BPFTRACE_RUNTIME_TEST_EXECUTABLE at the symlink.
#
# Requirements:
#   * BPFTRACE_SRC points at a bpftrace checkout (default: ~/git/bpftrace).
#   * That checkout has been built once (the engine imports cmake_vars
#     which is generated by bpftrace's CMake build).
#   * python3 with the `looseversion' package installed
#     (`pip install --user looseversion').
#   * sudo for probe attach (most non-`-l` tests load BPF programs).
#
# Pass an optional gtest-style filter via TEST_FILTER, e.g.
#   make bpftrace-runtime-test TEST_FILTER='basic.*'
BPFTRACE_SRC ?= $(HOME)/git/bpftrace
bpftrace-runtime-test: whistler
	@ln -sf $(CURDIR)/whistler $(CURDIR)/scripts/bpftrace
	@# Engine ships its own un-rendered cmake_vars.py template that
	@# Python refuses to parse. Stage the engine + our shim under
	@# build/ so the import path resolves cleanly without touching
	@# the bpftrace checkout.
	@mkdir -p build/bpftrace-runtime-engine
	@cp $(BPFTRACE_SRC)/tests/runtime/engine/main.py \
	    $(BPFTRACE_SRC)/tests/runtime/engine/parser.py \
	    $(BPFTRACE_SRC)/tests/runtime/engine/runner.py \
	    build/bpftrace-runtime-engine/
	@cp scripts/cmake_vars_shim.py build/bpftrace-runtime-engine/cmake_vars.py
	@cd $(BPFTRACE_SRC)/tests && \
	  BPFTRACE_RUNTIME_TEST_EXECUTABLE=$(CURDIR)/scripts/bpftrace \
	  python3 -u $(CURDIR)/build/bpftrace-runtime-engine/main.py \
	    $(if $(TEST_FILTER),--filter "$(TEST_FILTER)",)

# Interactive REPL with whistler loaded
repl:
	$(SBCL) --noinform \
		--eval '(require :asdf)' \
		--eval '(push #p"./" asdf:*central-registry*)' \
		--eval '(asdf:load-system "whistler")' \
		--eval '(in-package #:whistler-user)'

# Interactive REPL with compiler and loader loaded
repl-loader:
	$(SBCL) --noinform \
		--eval '(require :asdf)' \
		--eval '(push #p"./" asdf:*central-registry*)' \
		--eval '(asdf:load-system "whistler/loader")' \
		--eval '(in-package #:whistler-loader-user)'

clean:
	rm -f whistler
	rm -f examples/*.bpf.o
	rm -f *.fasl
